name: shared
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:


    sdk: flutter
  url_launcher: ^6.1.11
  cloud_firestore: ^4.13.3
  logger: ^2.0.1
  firebase_auth: ^4.10.1
  google_maps_flutter: ^2.3.0
  flutter_bloc: ^8.1.3
  auto_route: ^7.4.0
  http: ^1.1.0
  map_launcher: ^3.1.0
  freezed_annotation: ^2.2.0
  flutter_svg: ^2.0.6
  flutter_local_notifications: ^16.1.0
  firebase_messaging: ^14.7.4
  get_it: ^7.6.4
  build_runner: ^2.4.5
  custom_lint: any
  latlong2: ^0.9.0
  freezed: ^2.3.5
  json_serializable: ^6.7.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
