name: homyyy
description: "App gpr home"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  app_links: ^3.4.3
  auto_route: ^7.4.0
  auto_size_text: ^3.0.0
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.13.1
  dio: ^5.3.3
  collection: ^1.17.1
  connectivity_plus: ^4.0.2
  equatable: ^2.0.5
  firebase_app_check: ^0.2.1+4
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  firebase_messaging: ^14.7.4
  firebase_remote_config: ^4.3.4
  firebase_storage: ^11.5.1
  flutter_local_notifications: ^16.1.0
  uuid: ^4.2.1
  flutter_svg: ^2.0.6
  freezed_annotation: ^2.2.0
  image_picker: ^1.0.4
  retrofit: ^4.0.3
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  logger: ^2.0.1
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  pinput: ^3.0.1
  easy_localization: ^3.0.2
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  pull_to_refresh_flutter3: ^2.0.2
  rxdart: ^0.27.7
  shared:
    path: packages/shared
  chat:
    path: packages/chat
  uikit:
    path: packages/uikit

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  freezed: ^2.4.6
  json_serializable: ^6.7.0
  flutter_native_splash: ^2.3.1
  auto_route_generator: ^7.1.1
  custom_lint: any
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  retrofit_generator: ^7.0.8


flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
  uses-material-design: true
