name: uikit
version: 0.0.1+3
description: A new Flutter package project.
environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=1.17.0'
dependencies:
  collection: ^1.17.2
  expandable_page_view: ^1.0.17
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  google_fonts: ^5.1.0
  intl: ^0.18.1
  liquid_pull_to_refresh: ^3.0.1
  shimmer: ^3.0.0
  flutter_multi_formatter: ^2.11.6
  mask_text_input_formatter: ^2.7.0


  sticky_headers: ^0.3.0+2


dev_dependencies:
  build_runner: any
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  pubspec_dependency_sorter: ^1.0.4

flutter_gen:
  output: lib/gen/
  assets:
    outputs:
      package_parameter_enabled: true
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false
  line_length: 80
flutter:
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
  uses-material-design: true
  generate: true
