name: chat
description: "A new Flutter package project."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.3.0-187.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.10
  flutter_bloc: ^8.1.3
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  get_it: ^7.6.4
  uikit:
    path: ../uikit
  shared:
    path: ../shared
  uuid: ^4.2.1
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  custom_lint: any
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.8
  flutter_lints: ^3.0.0

flutter:

